./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
./dummy_test >> log.txt
